# Variables
MAIN_FILE = main.cpp
OUTPUT_FILE = main.exe
CXX = g++
CXXFLAGS = -O1 -Wall -std=c99 -Wno-missing-braces -I ..\inc -L ..\lib
LIBS = -lraylib -lopengl32 -lgdi32 -lwinmm
OBJ_FILES = $(MAIN_FILE:.cpp=.o)

# Target to build the project
all: $(OUTPUT_FILE)

$(OUTPUT_FILE): $(OBJ_FILES)
	$(CXX) $(CXXFLAGS) -o $(OUTPUT_FILE) $(OBJ_FILES) $(LIBS)

# Compile .cpp files into .o object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean target to remove autogenerated files
clean:
	del /Q *.o $(OUTPUT_FILE)

# Phony targets (non-file targets)
.PHONY: all clean
